### ISSUE TITLE
Android app unable to show existing posts

### ISSUE THREAD

**Issue by joncojonathan** [TryGhost/Ghost-Android#25]
- Ghost version: 1.23.0
- App version: 1.1.3
- Android version: 7.0
- Motorola Moto G5

----

On logging in to Ghost (self hosted) with the app I'm unable to view existing posts.  Instead I receive a toast which says `Couldn't refresh data`.  This seems to come from the `onDataRefreshedEvent()` method of `PostListActivity.java`.

What is interesting is that I can create a new draft and that appears in the Ghost web UI, so clearly there is some communication working.  Similarly, my correct blog name and avatar show in the app.

According to my webserver, the following has happened on the refresh request:

<pre>
[30/May/2018:19:57:35 +0000] "GET /ghost/api/v0.1/settings/?type=blog HTTP/1.1" 304 0 "-" "okhttp/3.9.0"

[30/May/2018:19:57:35 +0000] "GET /ghost/api/v0.1/users/me/?include=roles&status=all HTTP/1.1" 304 0 "-" "okhttp/3.9.0"

[30/May/2018:19:57:35 +0000] "GET /ghost/api/v0.1/posts/?status=all&staticPages=all&include=tags&formats=mobiledoc,html&limit=30 HTTP/1.1" 200 14418 "-" "okhttp/3.9.0"
</pre>

If I delete the draft in the web UI the app still shows it as existing.  Editing the draft on the phone and saving it again as a draft results in `saved on device, waiting to go online...`.

Any advice would be appreciated.  Happy to assist with troubleshooting but I don't have another Ghost instance to experiment with.

**Comment by vickychijwani** [comment]
Hey @joncojonathan :wave: 

I'm guessing you're using [the new Koenig editor beta](https://forum.ghost.org/t/koenig-editor-beta-release/1284)? The Android app cannot handle posts created with Koenig yet :slightly_smiling_face: 

I do see some errors today from a Moto G5 running Android 7.0 in our error-reporting tool: http://crashes.to/s/a509979bbbe. Partial stack trace:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference
       at me.vickychijwani.spectre.network.GhostApiUtils.mobiledocToMarkdown(GhostApiUtils.java:110)
       ...
```

Which points to this function:

https://github.com/TryGhost/Ghost-Android/blob/cdf899bad70cd43da2312f1069af601e38ac61c0/app/src/main/java/me/vickychijwani/spectre/network/GhostApiUtils.java#L103-L111

So it looks like one of your posts doesn't match the format the app expects - it failed to find the `markdown` field. This is what the app _expects_ to find in the `mobiledoc` field of each post:

```
{
  "version": "0.3.1",
  "markups": [],
  "atoms": [],
  "cards": [[
    "card-markdown",
    {
      "cardName": "card-markdown",
      "markdown": "post body text goes here"   <-- this is the important part
    }
  ]],
  "sections": [[10,0]]
}
```

I can probably release an update to ignore posts that are not 100% markdown (i.e., if they're using other features of the new Koenig editor) if you can confirm this is the source of the issue.

**Comment by jlelse** [comment]
I have the same problem, but I think it wouldn't be optimal to just hide the posts created with Koenig. Why don't do it like the Medium app, support normal text but not cards (like HTML etc..)?

**Comment by vickychijwani** [comment]
@jlelse it's not optimal, but it's a start. I would rather begin with a simple fix (ignore Koenig posts) so users can at least see their other posts and continue to edit those. Then we can move on to the question of what aspects of Koenig to support in the Android app.

Rendering posts created with Koenig is going to be a non-trivial change because it's no longer a simple markdown => HTML conversion, and editing support is going to take even more effort. I looked at the Medium app just now - your suggestion makes sense, so we can aim for something like that eventually :slightly_smiling_face:

**Comment by vickychijwani** [comment]
> Is there any other testing I can do to help you?

Nothing else, I guess. I'll go test some stuff :hammer_and_wrench:

**Comment by joncojonathan** [comment]
Looks like Koenig Is going to be the default editor (
https://forum.ghost.org/t/koenig-editor-beta-release/1284). I'm still new
to ghost...

**Comment by joncojonathan** [comment]
Looks like the problem is still present. Is there anything I can do to help?

Currently testing with Ghost version 1.24.7 and Android app version 1.1.3.

**Comment by Pixelfahnder** [comment]
I also discover a similar behaviour. Looking in the Android debug output I see the following error occuring:

`07-22 11:03:26.974 2873-2873/? E/Exception: java.lang.NullPointerException
        at me.vickychijwani.spectre.network.GhostApiUtils.mobiledocToMarkdown(GhostApiUtils.java:110)
        at me.vickychijwani.spectre.network.PostTypeAdapterFactory$1.read(PostTypeAdapterFactory.java:47)
        at me.vickychijwani.spectre.network.PostTypeAdapterFactory$1.read(PostTypeAdapterFactory.java:27)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)
07-22 11:03:26.974 2873-2873/? E/PostListActivity: Generic error message triggered during refresh
07-22 11:03:26.990 2873-2873/? E/Exception: me.vickychijwani.spectre.error.SyncException: SYNC EXCEPTION: sync failed, see previous exception for details
        at me.vickychijwani.spectre.view.PostListActivity.onDataRefreshedEvent(PostListActivity.java:289)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
        at com.squareup.otto.Bus.dispatch(Bus.java:385)
        at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
        at com.squareup.otto.Bus.post(Bus.java:337)
        at me.vickychijwani.spectre.network.NetworkService.refreshDone(NetworkService.java:960)
        at me.vickychijwani.spectre.network.NetworkService.refreshFailed(NetworkService.java:951)
        at me.vickychijwani.spectre.network.NetworkService.access$700(NetworkService.java:96)
        at me.vickychijwani.spectre.network.NetworkService$4.onFailure(NetworkService.java:445)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at me.vickychijwani.spectre.network.GhostApiUtils.mobiledocToMarkdown(GhostApiUtils.java:110)
        at me.vickychijwani.spectre.network.PostTypeAdapterFactory$1.read(PostTypeAdapterFactory.java:47)
        at me.vickychijwani.spectre.network.PostTypeAdapterFactory$1.read(PostTypeAdapterFactory.java:27)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)`

**Comment by vickychijwani** [comment]
I've released v1.2.0-beta1 of the app which fixes the "couldn't refresh" issue and can edit pure-markdown posts created with Koenig (in addition to pre-Koenig posts). In this context a "pure markdown Koenig post" means one containing a single Markdown card and nothing else. For any other Koenig posts, the app will display a message saying they cannot be edited.

@joncojonathan @jlelse @Pixelfahnder would you be able to test it and report any issues with it? To try it out, go to https://play.google.com/apps/testing/org.ghost.android and click "Become a tester".

**Comment by joncojonathan** [comment]
@vickychijwani I've installed that and I'm now presented with a list of posts.

- As stated, attempting to edit a post written in the Koenig editor, with more than one card, produces a messaging saying it cannot be edited in the app.
- Possibly unexpected: if there's a Koenig post that starts with a markdown card, but then has additional cards, only the first card shows.
- Post banner images show, along with the post name and tags

I'm assuming Koenig support is in the works?  I'll work on a new post with the app and let you know how that goes.

**Comment by vickychijwani** [comment]
> Possibly unexpected: if there's a Koenig post that starts with a markdown card, but then has additional cards, only the first card shows.

@joncojonathan Can you share the mobiledoc from that post? In my testing with the following post, I see the "cannot edit Koenig post" message as expected:

```json
{"version":"0.3.1","atoms":[],"cards":[
  ["markdown",{"markdown":"**bold** _italic_"}],
  ["code",{"code":"int x = 5"}]
],"markups":[],"sections":[[10,0],[10,1],[1,"p",[]]]}
```

**Comment by joncojonathan** [comment]
@vickychijwani I'm possibly being dumb, but what do you mean by the _mobiledoc_ in this case please?

**Comment by joncojonathan** [comment]
@vickychijwani here you go, thanks for the instructions:

``
mobiledoc | {"version":"0.3.1","atoms":[],"cards":[["card-markdown",{"cardName":"card-markdown","markdown":"It's  worrying that people still consider an email signature to be ID.  On a  recent call to a client they told me a third party should just speak to  me because my email signature stated who I worked for, so here I'm going  to discuss why that's a flawed  assumption."}]],"markups":[["em"],["code"]],"sections":[[10,0],[1,"p",[[0,[],0,"In  the case of my recent conversation I was talking to a client about why I  couldn't…ng Domain Keys Identified Mail although this requires support  on the sending mail server, and checks to be made by the  recipient."]]],[1,"p",[[0,[],0,"In order to validate me we can use  various trust models, for PGP's "],[0,[0],1,"web of trust"],[0,[],0,".   This falls down if you don't trust anyone who trusts me, but the basic  principle is that if you trust Alice, and Alice tells says to you \"this  is Bob\" then you attribute a level of confidence that the person  you're introduced to is indeed Bob.  "]]]]}
-- | --
``

That's unedited.

**Comment by joncojonathan** [comment]
@vickychijwani Additonally, if I start a post in the app and then move to edit it in the web application (where I've enabled Koenig) I can see a single Markdown card as you'd expect.

If I then add a new paragraph (creating a new card) and then sync back to my phone, I cannot see the new card at all.  Editing the post on the phone again (working in the original MD card) and adding a line or two works and saves fine.  When I then look at it in the web app again my new text is present in the MD card and the new card I added on the PC (but couldn't see on the phone) is also present, unaffected.

The text in the new card I added in Koenig is `New card` and shows in the mobiledoc (below, unedited):

``
mobiledoc | {"version":"0.3.1","atoms":[],"cards":[["card-markdown",{"cardName":"card-markdown","markdown":"Not  too long ago, Ransomware was the big threat to individuals a  businesses.  It was a regular problem I saw come up online and in  support tickets: a taunting full screen warning advising all their files  were encrypted.  Ransomware doesn't seem to be the weapon of choice any  more, but is it still a threat?\n\nBlah blah  blah\n\n"}]],"markups":[],"sections":[[10,0],[1,"p",[[0,[],0,"New  card"]]]]}
-- | --
``

**Comment by vickychijwani** [comment]
Ah, I was assuming post content would always be _inside_ a card, but that's clearly not the case. Looking closely at the [mobiledoc format](https://github.com/bustle/mobiledoc-kit/blob/master/MOBILEDOC.md#sections), a post with a single card will always have `{ "sections": [[10, 0]] }`, so I need to add a constraint for that as well.

Thanks for catching this @joncojonathan! I'll upload a new beta shortly.

**Comment by vickychijwani** [comment]
v1.2.0-beta2 is up.

**Comment by vickychijwani** [comment]
v1.2.0 is rolling out to everyone now.

**Comment by Angristan** [comment]
Thanks!

**Comment by JimmyBoh** [comment]
@vickychijwani Is full support for the new mobiledoc format on the roadmap? Is there anything we (the community) can do to help to get that implemented?

**Comment by vickychijwani** [comment]
@JimmyBoh Hi! 👋I opened a new issue #41 for discussions on mobiledoc support. Hopefully that should answer your question - I'm happy to discuss further and hear suggestions.

PS: If you have any further comments, please add them over there. Thanks!
