### ISSUE TITLE
[Crash] SettingRealmProxy - Trying to set non-nullable field 'value' to null

### ISSUE THREAD

**Issue by imajou** [TryGhost/Ghost-Android#38]
- Ghost version: 2.14.3 (self-hosted)
- App version: 1.2.2
- Android version: 9.0
- Device: Samsung Galaxy S8 (SM-G950F)

----

App crashes in main menu after successful log-in.
Cannot say any more, I am not familiar with Realm.

----

Stack trace:

```
FATAL EXCEPTION: main
Process: org.ghost.android, PID: 19607
java.lang.IllegalArgumentException: Trying to set non-nullable field 'value' to null.
	at io.realm.SettingRealmProxy.realmSet$value(SettingRealmProxy.java:191)
	at io.realm.SettingRealmProxy.copy(SettingRealmProxy.java:442)
	at io.realm.SettingRealmProxy.copyOrUpdate(SettingRealmProxy.java:428)
	at io.realm.BlogDataModuleMediator.copyOrUpdate(BlogDataModuleMediator.java:232)
	at io.realm.Realm.copyOrUpdate(Realm.java:1505)
	at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1143)
	at me.vickychijwani.spectre.network.NetworkService.lambda$createOrUpdateModel$5$NetworkService(NetworkService.java:1062)
	at me.vickychijwani.spectre.network.NetworkService$$Lambda$5.execute(Unknown Source:6)
	at me.vickychijwani.spectre.model.RealmUtils.executeTransaction(RealmUtils.java:30)
	at me.vickychijwani.spectre.network.NetworkService.createOrUpdateModel(NetworkService.java:1061)
	at me.vickychijwani.spectre.network.NetworkService.createOrUpdateModel(NetworkService.java:1053)
	at me.vickychijwani.spectre.network.NetworkService.access$200(NetworkService.java:96)
	at me.vickychijwani.spectre.network.NetworkService$3.onResponse(NetworkService.java:325)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

**Comment by vickychijwani** [comment]
Hi @imajou! 👋

Thanks for the bug report. I'm aware of the issue and am working on a fix for this.

**Comment by vickychijwani** [comment]
Full crash statistics and other details: http://crashes.to/s/abcf16a79b4
